/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description initData authentication is supplied in the JSON body. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DownloadRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DownloadResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authentication or access denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Queue or request limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    before?: number;
                    before_id?: string;
                    status?: string;
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HistoryResponse"];
                    };
                };
                /** @description Invalid cursor */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authentication or access denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    job_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Action accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authentication or access denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No accessible job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Job state does not allow this action */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Queue or request limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    job_id: string;
                };
                cookie?: never;
            };
            /** @description Explicit acknowledgement when a previous delivery may have succeeded. */
            requestBody?: {
                content: {
                    "application/json": {
                        /** @default false */
                        confirm_duplicate_risk?: boolean;
                    };
                };
            };
            responses: {
                /** @description Action accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authentication or access denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No accessible job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Job state does not allow this action */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Queue or request limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DownloadRequest */
        DownloadRequest: {
            /**
             * Initdata
             * @default
             */
            initData: string;
            /** Url */
            url: string;
            /**
             * Mode
             * @default video
             */
            mode: string;
            /**
             * Quality
             * @default null
             */
            quality: number | null;
            /**
             * Abr
             * @default null
             */
            abr: number | null;
        };
        /** DownloadResponse */
        DownloadResponse: {
            /** Ok */
            ok: boolean;
            /** Queued */
            queued: number;
            /** Job Ids */
            job_ids: string[];
        };
        /** FailureInfo */
        FailureInfo: {
            kind: components["schemas"]["FailureKind"];
            /** Message Key */
            message_key: string;
            /** Retryable */
            retryable: boolean;
        };
        /**
         * FailureKind
         * @enum {string}
         */
        FailureKind: "auth_required" | "unavailable" | "rate_limited" | "network" | "extractor" | "resource" | "unknown";
        /** JobView */
        JobView: {
            /** Id */
            id: string;
            /** User Id */
            user_id: number | null;
            /** Chat Id */
            chat_id: number | null;
            /** Ts */
            ts: number;
            /** Updated */
            updated: number;
            /** Source */
            source: string;
            /** Mode */
            mode: string;
            /** Status */
            status: string;
            /**
             * Pct
             * @default null
             */
            pct: number | null;
            /**
             * Url
             * @default null
             */
            url: string | null;
            /** @default null */
            failure: components["schemas"]["FailureInfo"] | null;
        } & {
            [key: string]: unknown;
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Ok */
            ok: boolean;
            /** Jobs */
            jobs: components["schemas"]["JobView"][];
            /** Next Before */
            next_before: number | null;
            /** Next Before Id */
            next_before_id: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
